dataset_root: /data/algonauts_2023_challenge_data
output_root: ./results
subject: 1
run_name: subj{subject:02d}_tben
distributed: false
batch_size: 16
num_workers: 4
val_ratio: 0.1
seed: 0
pretrained_backbone: false
hidden_dim: 256
decoder_layers: 1
encoder_layers: 0
enc_output_layer: -1
nheads: 8
dim_feedforward: 1024
dropout: 0.1
backbone_name: dinov2_q
readout_name: tben
